-- 30 additional Pokémon card inserts
INSERT INTO tbl_cards (collection_id, hp, name, type, stage, info, damage, weak, resist, retreat, card_number_in_collection) VALUES
(1, 40, 'Pidgey', 'Colorless', 'Basic', 'Small bird Pokémon with gust attack', '10', 'Electric', NULL, 1, '57/102'),
(1, 80, 'Pidgeotto', 'Colorless', 'Stage 1', 'Evolution of Pidgey with stronger gust', '40', 'Electric', NULL, 1, '22/102'),
(1, 100, 'Machamp', 'Fighting', 'Stage 2', 'Strong fighter Pokémon with seismic toss', '60', 'Psychic', NULL, 3, '8/102'),
(1, 90, 'Gengar', 'Psychic', 'Stage 2', 'Ghost Pokémon with curse ability', '70', 'Psychic', 'Fighting -30', 2, '5/102'),
(1, 60, 'Magikarp', 'Water', 'Basic', 'Weak fish Pokémon with splash', '10', 'Electric', NULL, 1, '61/102'),
(1, 100, 'Hitmonchan', 'Fighting', 'Basic', 'Punching Pokémon with jab attack', '40', 'Psychic', NULL, 2, '7/102'),
(2, 70, 'Nidoking', 'Fighting', 'Stage 2', 'Powerful jungle Pokémon with toxic attack', '80', 'Psychic', NULL, 3, '11/64'),
(2, 60, 'Paras', 'Grass', 'Basic', 'Mushroom Pokémon with spore attack', '20', 'Fire', NULL, 1, '47/64'),
(2, 80, 'Wigglytuff', 'Fairy', 'Stage 1', 'Evolution of Jigglypuff with singing powers', '50', 'Metal', NULL, 2, '32/64'),
(2, 90, 'Tauros', 'Colorless', 'Basic', 'Wild bull Pokémon with rampage attack', '60', 'Fighting', NULL, 2, '51/64'),
(2, 70, 'Dodrio', 'Colorless', 'Stage 1', 'Three-headed bird Pokémon with fury attack', '40', 'Electric', NULL, 1, '34/64'),
(3, 60, 'Graveler', 'Rock', 'Stage 1', 'Fossil Pokémon with rock throw', '30', 'Grass', NULL, 2, '37/62'),
(3, 80, 'Muk', 'Poison', 'Stage 1', 'Sludge Pokémon with toxic gas ability', '50', 'Psychic', NULL, 2, '13/62'),
(3, 100, 'Dragonite', 'Dragon', 'Stage 2', 'Rare fossil Pokémon with dragon rage', '90', 'Ice', NULL, 3, '4/62'),
(3, 70, 'Hypno', 'Psychic', 'Stage 1', 'Sleep-inducing Pokémon with hypnosis', '40', 'Psychic', NULL, 2, '8/62'),
(3, 90, 'Zapdos', 'Electric', 'Basic', 'Legendary bird Pokémon with thunder attack', '80', 'Ground', NULL, 2, '15/62'),
(4, 60, 'Mareep', 'Electric', 'Basic', 'Sheep Pokémon with static ability', '20', 'Ground', NULL, 1, '64/111'),
(4, 80, 'Quilava', 'Fire', 'Stage 1', 'Evolution of Cyndaquil with flame wheel', '40', 'Water', NULL, 2, '56/111'),
(4, 70, 'Bayleef', 'Grass', 'Stage 1', 'Evolution of Chikorita with vine whip', '30', 'Fire', NULL, 2, '54/111'),
(4, 100, 'Meganium', 'Grass', 'Stage 2', 'Final evolution of Chikorita with solar beam', '80', 'Fire', NULL, 3, '6/111'),
(4, 90, 'Steelix', 'Metal', 'Stage 1', 'Steel snake Pokémon with iron tail', '70', 'Fire', 'Psychic -30', 4, '15/111'),
(4, 110, 'Lugia', 'Psychic', 'Basic', 'Legendary Pokémon with aeroblast', '90', 'Electric', NULL, 3, '9/111'),
(5, 210, 'Lapras V', 'Water', 'Basic', 'Sword & Shield V card with surf attack', '180', 'Electric', NULL, 2, '050/202'),
(5, 190, 'Morpeko V', 'Electric', 'Basic', 'Dual-nature Pokémon with spark attack', '150', 'Ground', NULL, 1, '037/202'),
(5, 200, 'Cinderace V', 'Fire', 'Stage 1', 'Soccer rabbit Pokémon with pyro ball', '170', 'Water', NULL, 2, '036/202'),
(5, 220, 'Rillaboom V', 'Grass', 'Stage 2', 'Drumming Pokémon with forest strike', '190', 'Fire', NULL, 3, '014/202'),
(5, 210, 'Snorlax V', 'Colorless', 'Basic', 'Sword & Shield V card with heavy slam', '200', 'Fighting', NULL, 4, '141/202'),
(5, 180, 'Toxtricity V', 'Electric', 'Stage 1', 'Punk Pokémon with shock attack', '160', 'Ground', NULL, 2, '070/202'),
(5, 200, 'Dragapult V', 'Dragon', 'Stage 2', 'Stealth dragon Pokémon with phantom force', '170', 'Ice', NULL, 2, '092/202'),
(5, 220, 'Eldegoss V', 'Grass', 'Basic', 'Cotton bloom Pokémon with healing ability', '160', 'Fire', NULL, 1, '019/202');
